### ISSUE TITLE
The app doesn't ask for storage access

### ISSUE THREAD

**Issue by Zirconium13** [fvasco/pinpoi#32]
Hello,
I'm having issues to add pois in the app.
The app doesn't have access to the storage of the phone, so impossible to add any pois in a collection.
Even in the settings, in the permission manager, I can't allow PINPOI to have access to the storage.
I have this error on the phone (Samsung Galaxy A32) when I click on the file I want to add :
Mime-Type: application/octet-stream

Do you have any idea how to solve that ?
Thank you very much

**Comment by fvasco** [comment]
Hello,
thanks for this issue.

Unfortunately, I am unable to reproduce, so I hope you help me, as best you can.

I updated PinPoi to support newer Google requirements, this task impacted on working import feature.
I suspect that your issue is unrelated to permission (due to the above task), but you are importing a file type unknown to your Galaxy.
What type of file you are trying to import?

I already tried to fix this in version 1.7.3, you can set the file type in the collection's screen, this should help.

If you are using an older version than 1.7.3, you can download an update from https://f-droid.org/it/packages/io.github.fvasco.pinpoi/
I strongly suggest you to perform a backup.

Please send me your feedback,
thank you.

Francesco

**Comment by Zirconium13** [comment]
Hello,

I'm trying to import ov2 files.
I tried to set the file type on ov2 and it works ! But if I set on "None (any)" it doesn't work.
Also, I don't have anymore to click on the button to load the file (on the top right of the screen) when it has just been added, I don't know why.

I thought there was an issue with permission because when I tried yesterday, when adding the file, I didn't get the in-app window to search for my files, instead I got the "My files" app from Samsung.
I was able to find the files but when clicking on them, I had the error I told you.

Sorry for some bad english, it's not my native language.

Thank you very much for your work !
Adrien
